apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.21-alpine3.17
        name: build
        kind: build
        shell: sh
        run: |
          echo "build"
  test:
    steps:
      - uses: docker://golang:1.21-alpine3.17
        kind: test
        name: test
        shell: sh
        run: |
          echo "test"
    needs:
      - build
  scan:
    steps:
      - uses: docker://golang:1.21-alpine3.17
        name: scan
        kind: scan
        shell: sh
        run: |
          echo "scan"
      - uses: cloudbees-io/trivy-scan-container@v1
        kind: scan
        with:
          image-location: public.ecr.aws/docker/library/hello-world
          image-tag: latest
    needs:
      - test
  deploy:
    steps:
      - uses: docker://golang:1.21-alpine3.17
        kind: deploy
        name: deploy
        shell: sh
        run: |
          echo "deploy"
    needs:
      - scan
